### ISSUE TITLE
Typst v0.3.0 移除了 after参数

### ISSUE THREAD

**Issue by evpeople** [QQKdeGit/bupt-typst#4]
https://github.com/QQKdeGit/bupt-typst/blob/fa9b38594fd1026f42cf768fd47b112e38d32e65/template.typ#L137

我手动删除了这行中的after，可以通过编译了，但是不确定具体起到了什么效果，是否还符合学校的格式

https://typst.app/docs/changelog/

**Comment by evpeople** [comment]
我看了一下文档，似乎应该是改成这个样子
```lex
query(selector(heading).after(loc), loc)
```

**Comment by QQKdeGit** [comment]
非常感谢

这是一个由 Typst 更新导致的 bug ，我已经在所有版本中修复它了
